name: Build Status

on:
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - LICENSE
      - README.md
  pull_request:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read
  checks: write
  pull-requests: write

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.11"]
        node-version: [22.x]

    steps:
    - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - uses: actions-ext/python/setup@main
      with:
        version: ${{ matrix.python-version }}

    - uses: actions-ext/node/setup@main
      with:
        version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: make develop

    - name: Lint
      run: make lint
      if: matrix.os == 'ubuntu-latest'

    - name: Checks
      run: make checks
      if: matrix.os == 'ubuntu-latest'

    - name: Build
      run: make build

    - name: Test
      run: make coverage
      if: matrix.os == 'ubuntu-latest'

    - name: Upload test results (Python)
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}-${{ matrix.node-version }}
        path: '**/junit.xml'
      if: ${{ always() }}

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@c950f6fb443cb5af20a377fd0dfaa78838901040 # v2
      with:
        files: '**/junit.xml'
      if: matrix.os == 'ubuntu-latest'

    - name: Upload coverage
      uses: codecov/codecov-action@e79a6962e0d4c0c17b229090214935d2e33f8354 # v6.0.1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Make dist
      run: make dist
      if: matrix.os == 'ubuntu-latest'

    - uses: actions-ext/python/test-wheel@main
      with:
        module: jupyterlab_templates
      if: matrix.os == 'ubuntu-latest'

    - uses: actions-ext/python/test-sdist@main
      with:
        module: jupyterlab_templates
      if: matrix.os == 'ubuntu-latest'

    - uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: dist-${{matrix.os}}
        path: dist
      if: matrix.os == 'ubuntu-latest'

