name: Copier Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Update from Copier
        uses: actions-ext/copier/update@2061209faa6b75ffd4fcecc0b0983772767997f4
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
