name: Copier Updates

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 * * 0"

jobs:
  update:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions-ext/copier-update@main
      with:
        token: ${{ secrets.WORKFLOW_TOKEN }}
